version: '3.2'

services:
  production-zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
        - "32181:32181"

  production-kafka:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - production-zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=production-zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://production-kafka:9092
    ports:
      - "9092:9092"
