## Run by NCSA
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: alerts-volume
#  labels:
#    lsst: alerts
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 2000Gi
#  accessModes:
#    - ReadWriteMany
#  nfs:
#    path: /lsst/kubernetes/shared/alert_data
#    server: 141.142.182.6

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-claim
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1950Gi
  storageClassName: manual
  selector:
    matchLabels:
      #lsst: "alerts"
      type: scratch 
status: {}

