apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: consumerall
  name: consumerall
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consumerall
    spec:
      containers:
      - args:
        - python
        - bin/printStream.py
        - kafka.alerts-lsst.svc.cluster.local:9092
        - full-stream
        - "100"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        image: lsst-kub001:5000/alert_stream
        name: consumerall
        resources: {}
      restartPolicy: Always
status: {}
