apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: filterer2
  name: filterer2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: filterer2
    spec:
      containers:
      - args:
        - python
        - bin/filterStream.py
        - full-stream
        - "21"
        - "40"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        image: alert_stream
        name: filterer2
        resources: {}
      restartPolicy: Always
status: {}
