apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          #value: PLAINTEXT://kafka:9092
          #value: PLAINTEXT://kafka.alerts-lsst.svc.cluster.local:9092
          #value: PLAINTEXT://141.142.181.185:9092
          value: PLAINTEXT://10.101.235.141:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:32181
        image: confluentinc/cp-kafka:4.1.1
        name: kafka
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
