apiVersion: apps/v1 #extensions/v1beta1
kind: Deployment
metadata:
  name: sender
spec:
  selector:
    matchLabels:
      app: sender
  replicas: 1
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender
        image: lsst-kub001:5000/alert_stream
        args:
        - python
        - bin/sendAlertStream.py
        - kafka.alerts-lsst.svc.cluster.local:9092
        - full-stream
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        #resources: {}
        volumeMounts:
        - mountPath: /home/alert_stream/data
          name: alert-volume
          subPath: mtpatter/avro_171213/ # data in /scratch/ for now
      restartPolicy: Always
      volumes:
      - name: alert-volume
        persistentVolumeClaim:
          claimName: alert-claim
status: {}
