apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: zookeeper
      name: zookeeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
        app: zookeeper
        name: zookeeper
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        image: confluentinc/cp-zookeeper:4.1.1
        name: zookeeper
        ports:
        - containerPort: 32181
        resources: {}
      restartPolicy: Always
status: {}
